In [13]:
from accelerator.tools.analysis.stats.collector import _WelfordCollector, VarianceTensorCollector

In [14]:
coll = _WelfordCollector(channel_dim=1, order=4)
var_coll = VarianceTensorCollector(channel_dim=1)

In [15]:
import torch

first_batch = torch.randn(8, 32, 224, 224)
second_batch = torch.randn(8, 32, 224, 224)

In [16]:
coll.update(first_batch)

In [17]:
coll._count

401408

In [18]:
first_batch.mean(dim=(0,2,3))

tensor([ 1.3397e-03,  2.9147e-04,  1.5996e-03,  3.8118e-04, -1.9746e-03,
         1.2940e-03, -3.3377e-04,  8.9642e-04,  8.7047e-04,  2.0782e-03,
        -2.6188e-04, -4.6257e-05, -2.4792e-05,  5.2362e-04, -6.8147e-04,
        -2.5562e-04, -5.5507e-04, -5.0091e-04,  1.6610e-03, -3.1882e-03,
        -1.9047e-03, -2.4072e-03,  2.4513e-03, -5.8952e-04, -4.4380e-07,
         5.8583e-04, -1.9041e-03, -1.5165e-03,  3.8007e-03,  2.0177e-03,
        -9.4402e-04, -1.2917e-03])

In [19]:
coll._mean

tensor([ 1.3397e-03,  2.9147e-04,  1.5996e-03,  3.8118e-04, -1.9746e-03,
         1.2940e-03, -3.3377e-04,  8.9642e-04,  8.7047e-04,  2.0782e-03,
        -2.6188e-04, -4.6257e-05, -2.4792e-05,  5.2362e-04, -6.8147e-04,
        -2.5562e-04, -5.5507e-04, -5.0091e-04,  1.6610e-03, -3.1882e-03,
        -1.9047e-03, -2.4072e-03,  2.4513e-03, -5.8952e-04, -4.4354e-07,
         5.8583e-04, -1.9041e-03, -1.5165e-03,  3.8007e-03,  2.0177e-03,
        -9.4402e-04, -1.2917e-03])

In [20]:
first_batch.var(dim=(0,2,3))


tensor([0.9977, 0.9968, 1.0046, 0.9986, 1.0032, 0.9984, 1.0025, 0.9983, 1.0021,
        1.0037, 0.9997, 0.9990, 0.9993, 1.0022, 0.9979, 0.9990, 0.9990, 1.0006,
        0.9996, 0.9992, 1.0026, 1.0046, 1.0028, 1.0034, 0.9987, 1.0015, 0.9987,
        0.9988, 0.9924, 1.0018, 0.9997, 0.9993])

In [25]:
coll._M2 / (coll._count - 1)

tensor([0.9977, 0.9968, 1.0046, 0.9986, 1.0032, 0.9984, 1.0025, 0.9983, 1.0021,
        1.0037, 0.9997, 0.9990, 0.9993, 1.0022, 0.9979, 0.9990, 0.9990, 1.0006,
        0.9996, 0.9992, 1.0026, 1.0046, 1.0028, 1.0034, 0.9987, 1.0015, 0.9987,
        0.9988, 0.9924, 1.0018, 0.9997, 0.9993])

In [8]:
second_batch.mean(dim=(0,2,3))

tensor([-2.0058e-03, -9.2894e-04, -2.7336e-03, -8.9105e-04,  4.1119e-04,
        -1.7545e-03, -7.0191e-05,  6.7377e-04, -2.5701e-04, -9.6031e-04,
        -1.6755e-03,  1.7869e-03, -2.6794e-04, -2.7576e-04, -7.5157e-04,
        -1.3311e-03,  1.3220e-03,  1.3928e-03,  1.0250e-03, -8.7519e-05,
         9.2005e-04,  1.4221e-03, -5.5949e-04,  4.5093e-03,  2.8277e-03,
         5.5922e-04,  9.6920e-04,  1.1156e-03,  5.7885e-04, -1.2281e-03,
         1.9176e-03,  7.6941e-04])

In [26]:
coll.update(second_batch)

In [27]:
coll._M2

tensor([803121.3750, 802447.6250, 804883.2500, 802054.6875, 804529.1250,
        802982.2500, 803137.7500, 801181.8125, 804105.8750, 805064.1250,
        803243.3750, 802946.3750, 803180.8750, 803812.6875, 801908.5000,
        801036.2500, 802286.3125, 802766.0625, 801865.6875, 801857.2500,
        803879.3125, 804241.2500, 803300.0000, 805696.5000, 803133.8750,
        804931.0625, 801551.0625, 803432.8750, 799153.5000, 803876.3750,
        802738.1875, 803466.6250])

In [30]:
(first_batch.var(dim=(0,2,3)) + second_batch.var(dim=(0,2,3))) / 2

tensor([1.0004, 0.9995, 1.0026, 0.9991, 1.0021, 1.0002, 1.0004, 0.9980, 1.0016,
        1.0028, 1.0005, 1.0002, 1.0005, 1.0012, 0.9989, 0.9978, 0.9993, 0.9999,
        0.9988, 0.9988, 1.0013, 1.0018, 1.0006, 1.0036, 1.0004, 1.0026, 0.9984,
        1.0008, 0.9954, 1.0013, 0.9999, 1.0008])

In [28]:
coll._M2 / (coll._count - 1)

tensor([1.0004, 0.9995, 1.0026, 0.9991, 1.0021, 1.0002, 1.0004, 0.9980, 1.0016,
        1.0028, 1.0005, 1.0002, 1.0005, 1.0012, 0.9989, 0.9978, 0.9993, 0.9999,
        0.9988, 0.9988, 1.0013, 1.0018, 1.0006, 1.0036, 1.0004, 1.0026, 0.9984,
        1.0008, 0.9954, 1.0013, 0.9999, 1.0008])